### ISSUE TITLE
PA Review: Main Feature (CRUD feature)

### ISSUE THREAD

**Issue by winterfreddy** [winterfreddy/somerslt#3]
## Functionality

- [x] If logged in, the user should be able to read any media blog
- [x] If logged in, the user should be able to read any media blog​ after any of the media blogs were updated
- [x] If logged in, the user should be able to post a text blog
- [x] If logged in, the user should be able to post a photo blog
- [x] If logged in, the user should be able to post a quote blog
- [x] If logged in, the user should be able to post a URL blog
- [x] If logged in, the user should be able to edit/update a text blog tied to that account signed into
- [x] If logged in, the user should be able to edit/update a photo blog tied to that account signed into
- [x] If logged in, the user should be able to edit/update a quote blog tied to that account signed into
- [x] If logged in, the user should be able to edit/update a URL blog tied to that account signed into
- [x] If logged in, the user should be able to delete a text blog tied to that account signed into
- [x] If logged in, the user should be able to delete a photo blog tied to that account signed into
- [x] If logged in, the user should be able to delete a quote blog tied to that account signed into
- [x] If logged in, the user should be able to delete a URL blog tied to that account signed into
- [x] If logged in, the user should not be able to modify or delete someone's blog post

**Comment by Vanchen07** [comment]
- ux suggestion would be to make the latest post show up top
- everything works and looks good!
